src/Entity/Vehicle.php
<?php

namespace App\Entity;

use App\Repository\VehicleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VehicleRepository::class)
 */
class Vehicle
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15,unique=true)
     */
    private $Matricula;




    /**
     * @ORM\Column(type="float")
     */
    private $Kilometres;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="vehicles")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Model::class, inversedBy="vehicles")
     */
    private $Model;

    /**
     * @ORM\OneToMany(targetEntity=Pressupost::class, mappedBy="vehicle")
     */
    private $pressuposts;

    /**
     * @ORM\OneToMany(targetEntity=OrdreReparacio::class, mappedBy="vehicle")
     */
    private $ordreReparacios;

    /**
     * @ORM\OneToMany(targetEntity=Factura::class, mappedBy="vehicle")
     */
    private $facturas;

    /**
     * @ORM\OneToMany(targetEntity=Agenda::class, mappedBy="vehicle")
     */
    private $agendas;



    public function __construct()
    {
        $this->pressuposts = new ArrayCollection();
        $this->ordreReparacios = new ArrayCollection();
        $this->facturas = new ArrayCollection();
        $this->agendas = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricula(): ?string
    {
        return $this->Matricula;
    }

    public function setMatricula(string $Matricula): self
    {
        $this->Matricula = $Matricula;

        return $this;
    }






    public function getKilometres(): ?float
    {
        return $this->Kilometres;
    }

    public function setKilometres(float $Kilometres): self
    {
        $this->Kilometres = $Kilometres;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getModel(): ?Model
    {
        return $this->Model;
    }

    public function setModel(?Model $Model): self
    {
        $this->Model = $Model;

        return $this;
    }

    /**
     * @return Collection|Pressupost[]
     */
    public function getPressuposts(): Collection
    {
        return $this->pressuposts;
    }

    public function addPressupost(Pressupost $pressupost): self
    {
        if (!$this->pressuposts->contains($pressupost)) {
            $this->pressuposts[] = $pressupost;
            $pressupost->setVehicle($this);
        }

        return $this;
    }

    public function removePressupost(Pressupost $pressupost): self
    {
        if ($this->pressuposts->removeElement($pressupost)) {
            // set the owning side to null (unless already changed)
            if ($pressupost->getVehicle() === $this) {
                $pressupost->setVehicle(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Matricula;
    }

    /**
     * @return Collection|OrdreReparacio[]
     */
    public function getOrdreReparacios(): Collection
    {
        return $this->ordreReparacios;
    }

    public function addOrdreReparacio(OrdreReparacio $ordreReparacio): self
    {
        if (!$this->ordreReparacios->contains($ordreReparacio)) {
            $this->ordreReparacios[] = $ordreReparacio;
            $ordreReparacio->setVehicle($this);
        }

        return $this;
    }

    public function removeOrdreReparacio(OrdreReparacio $ordreReparacio): self
    {
        if ($this->ordreReparacios->removeElement($ordreReparacio)) {
            // set the owning side to null (unless already changed)
            if ($ordreReparacio->getVehicle() === $this) {
                $ordreReparacio->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Factura[]
     */
    public function getFacturas(): Collection
    {
        return $this->facturas;
    }

    public function addFactura(Factura $factura): self
    {
        if (!$this->facturas->contains($factura)) {
            $this->facturas[] = $factura;
            $factura->setVehicle($this);
        }

        return $this;
    }

    public function removeFactura(Factura $factura): self
    {
        if ($this->facturas->removeElement($factura)) {
            // set the owning side to null (unless already changed)
            if ($factura->getVehicle() === $this) {
                $factura->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Agenda[]
     */
    public function getAgendas(): Collection
    {
        return $this->agendas;
    }

    public function addAgenda(Agenda $agenda): self
    {
        if (!$this->agendas->contains($agenda)) {
            $this->agendas[] = $agenda;
            $agenda->setVehicle($this);
        }

        return $this;
    }

    public function removeAgenda(Agenda $agenda): self
    {
        if ($this->agendas->removeElement($agenda)) {
            // set the owning side to null (unless already changed)
            if ($agenda->getVehicle() === $this) {
                $agenda->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * String representation of object
     * @return string the string representation of the object or null
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->Matricula,
        ]);
    }
}

src/Form/AgendaType.php
<?php

namespace App\Form;

use App\Entity\Agenda;
use DateTime;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\{CollectionType, TextType, NumberType, DateTimeType, ChoiceType, TextareaType};
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\{Vehicle, User};



class AgendaType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            //->add('dataHora', DateTimeType::class, ['label' => 'Data/Hora ','widget' => 'choice',])
            ->add('dataHoraInici', TextType::class, [

                'required' => true,
                'label' => 'Inici',
                //'translation_domain' => 'AppBundle',
                'attr' => [
                    'class' => 'form-control input-inline form_datetime',
                    'data-provide' => 'datetimepicker',
                    'data-format' => 'dd-mm-yyyy HH:ii',
                ],
            ])
            ->add('dataHoraFi', TextType::class, [

                'required' => false,
                'label' => 'Fi',
                //'translation_domain' => 'AppBundle',
                'attr' => [
                    'class' => 'form-control input-inline form_datetime',
                    'data-provide' => 'datetimepicker',
                    'data-format' => 'dd-mm-yyyy HH:ii',
                ],
            ])
            ->add(
                'vehicle',
                EntityType::class,
                [
                    'label' => 'Vehicle',
                    'class' => Vehicle::class,

                ]
            )
            ->add('treballador', TextType::class, [
                'disabled' => true,

            ])
            ->add('allDay')
            ->add('feina')
            ->add('observacions')
            ->add('estat', ChoiceType::class, [

                'choices' => [
                    'Pendent' => 0,
                    'Completada' => 1,
                    'Anulada' => 2

                ],
                'label' => 'Tasca',

            ])
            ->addEventListener(FormEvents::POST_SET_DATA,function(FormEvent $event){
                $form = $event->getForm();
                $agenda= $event->getData();

                if($agenda==null || $agenda->getId() ==null){
                    return;
                }
                if($agenda instanceof Agenda){
                    $form->get('dataHoraInici')->setData($agenda->getdataHoraInici()->format('Y-m-d G:i'));
                    $form->get('dataHoraFi')->setData($agenda->getdataHoraFi()->format('Y-m-d G:i'));
                }

            })
            ->addEventListener(FormEvents::PRE_SUBMIT, function (FormEvent $event) {
                $e = $event->getData();
                $dataIni = $e['dataHoraInici'];
                $dataIniOk = new DateTime($dataIni);
                $e['dataHoraInici'] = $dataIniOk;

                $dataFi = $e['dataHoraFi'];
                $dataFiOk = new DateTime($dataFi);
                $e['dataHoraFi'] = $dataFiOk;
                $event->setData($e);
            });
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Agenda::class,
        ]);
    }
}

src/Controller/AgendaController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\{Agenda, User, Factura, Empresa, OrdreReparacio};
use App\Form\AgendaType;

use Omines\DataTablesBundle\Column\{TextColumn, DateTimeColumn};
use Omines\DataTablesBundle\DataTableFactory;
use Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter;
use Symfony\Component\Validator\Validator\ValidatorInterface;
use App\Controller\BaseController;
use Symfony\Component\Security\Core\User\UserInterface;


use Symfony\Component\Serializer\Encoder\JsonEncoder;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Validator\Constraints\DateTime;

class AgendaController extends BaseController
{


    /**
     * @Route("agenda/event/modificar/{id}", name="modificar_event")
     */
    public function modificarEvent(Request $request, Agenda $agenda): Response
    {


        $form = $this->createForm(AgendaType::class, $agenda);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->addFlash('success', 'agenda.success-edit');
            $this->save($agenda);


            return $this->redirectToRoute('agenda',['id'=>$agenda->getTreballador()->getId()]);
        }

        return $this->render('agenda/modificar_agenda.html.twig', ['form' => $form->createView(), 'agenda' => $agenda]);
    }

    /**
     * @Route("/agenda/event/esborrar/{id}",name="esborrar_event")
     */
    public function esborrarEvent(Request $request, Agenda $agenda):Response{
        $agendaUsuari = $agenda->getTreballador();
        $resultat = $this->esborrar($agenda);


        if (!$resultat) {
            $this->addFlash('error', 'agenda.error-del');
        }
        $this->addFlash('success', 'agenda.success-del');
        return $this->redirectToRoute('agenda',['id'=>$agendaUsuari->getId()]);
    }



    /**
     * @Route("/agenda/events", name="llistar_events")
     */
    public function llistar_events(Request $request, DataTableFactory $dataTableFactory): Response
    {
        $table = $dataTableFactory->create()

            ->add('feina', TextColumn::class, ['label' => 'Tasca',  ])
            ->add('vehicle', TextColumn::class, ['label' => 'Vehicle', 'searchable' => True, 'field' => 'vehicle.Matricula'])
            ->add('dataHoraInici', DateTimeColumn::class, ['label' => 'Data/hora', ])
            ->add('dataHoraFi', DateTimeColumn::class, ['label' => 'Data/hora',])
            ->add('treballador', TextColumn::class, ['label' => 'Treballador', 'field' => 'treballador.nom'])
            ->add('estat', TextColumn::class, ["visible" => false, 'label' => 'Estat pagament', 'render' => function ($value, $context) {
                $action = "";
                if ($value == 0) {
                    $action = "<p class='text-danger'>Pendent</p>";
                } else if ($value == 1) {
                    $action = "<p class='text-success'>Completada</p>";
                } else {
                    $action = "<p class='text-secondary'>Anulada</p>";
                }

                return $action;
            }])
            ->add('id', TextColumn::class, ['label' => '', 'searchable' => True, 'orderable' => True, 'render' => function ($value, $context) {


                $action = "";
                if ($value < 10) {
                    $action = '0';
                }
                $action = $action . $value . ' 
                        <div class="btn-group">
                            <a href="/agenda/events/' . $value . '" class="badge badge-secondary p-2 m-1">Veure event</a>
                            <a href="/agenda/event/modificar/' . $value . '" class="badge badge-secondary p-2 m-1">Modificar event</a>
                            <a href="/agenda/event/esborrar/' . $value . '/pdf" class="badge badge-danger p-2 m-1">Eliminar event</a>
                        </div>';


                return $action;
            }])
            //->addOrderBy(5, 'desc')
            ->createAdapter(ORMAdapter::class, [
                'entity' => Agenda::class,
            ])
            ->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getResponse();
        }

        return $this->render('agenda/llistar.html.twig', ['datatable' => $table]);
    }


    

    /**
     * @Route("/agenda/afegir",name="afegir_event")
     */
    public function createTasca(Request $request, ValidatorInterface $validator): Response
    {

        $usuari_id = $request->query->get('usuari');
        $usuari = $this->getDoctrine()->getRepository(User::class)->find($usuari_id);
        $agenda = new Agenda();
        $agenda->setTreballador($usuari);

        $form = $this->createForm(AgendaType::class, $agenda);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
           
            $this->save($agenda);
            $this->addFlash('success', 'agenda.success-add');
            return $this->redirectToRoute('agenda');
        }

        return $this->render('agenda/afegir.html.twig', ['form' => $form->createView()]);
    }



    /**
     * @Route("/agenda/{id}", defaults={"id"=-1}, name="agenda")
     * @Route("/",  name="agenda_home")
     */
    public function index(Request $request, User $user = null, UserInterface $userActual): Response
    {
        $routeName = $request->attributes->get('_route');

        if($routeName == "agenda_home"){
                $user = $userActual;
        }

        if ($user) {
            return $this->render('agenda/agenda.html.twig', [
                'controller_name' => 'AgendaController',
                'user' => $user
            ]);
        } else {
            
            $usuaris = $this->getDoctrine()
                ->getRepository(User::class)
                ->findAll();
            return $this->render('agenda/index.html.twig', [
                'usuaris' => $usuaris
            ]);
        }
    }

    /**
     * @Route("/agenda/event/{id}",name="agenda_show")
     */
    public function show(Agenda $agenda): Response
    {
        return $this->render('agenda/fitxa_agenda.html.twig', [
            'controller_name' => 'AgendaController',
            'agenda' => $agenda,
        ]);
    }
}

templates/agenda/afegir.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'agenda.add'|trans }}
{% endblock %}
{% block title_block %}
  {{ 'agenda.add'|trans }}
{% endblock %}


{% block body %}
  <div class="pt-2">
    {{ form_start(form) }}
    {{ form_row(form.feina) }}
    {{ form_row(form.dataHoraInici) }}
    {{ form_row(form.dataHoraFi) }}
    {{ form_row(form.vehicle) }}
    {{ form_row(form.treballador) }}
    {{ form_row(form.estat) }}

    {{ form_rest(form) }}

    <div class="w-100 text-center">
      <button type="submit" class="btn btn-outline-primary">
        <i class="fa fa-paper-plane"></i> Enviar
      </button>
    </div>

    {{ form_end(form) }}
  </div>
{% endblock %}

{% block javascripts %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js"
    integrity="sha512-LGXaggshOkD/at6PFNcp2V2unf9LzFq6LE+sChH7ceMTDP0g2kn6Vxwgg7wkPP7AAtX+lmPqPdxB47A0Nz0cMQ=="
    crossorigin="anonymous"></script>
  <script src="/build/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript"
    src="/build/bootstrap-datetimepicker.es.js"
    charset="UTF-8"></script>

  <script>
    $(document).ready(function () { $(".form_datetime").datetimepicker({
    language: 'ES' }); })
  </script>
{% endblock %}

templates/agenda/agenda.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'agenda.agenda'|trans }}: {{ user.nom }}
{% endblock %}
{% block title_block %}
  {{ 'agenda.agenda'|trans }}: {{ user.nom }}
{% endblock %}

{% block stylesheets2 %}
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fullcalendar@5.6.0/main.min.css"> -->
  <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap/main.min.css">

    <link href='https://cdn.jsdelivr.net/npm/@fullcalendar/core/main.css' rel='stylesheet' />
	<link href='https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid/main.css' rel='stylesheet' />
	<link href='https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap/main.css' rel='stylesheet' />

    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core/locales/es.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/bootstrap/main.min.js"></script> -->

  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.css" />
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.css" />
  <link rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.css" />

    <link href='https://cdn.jsdelivr.net/npm/bootstrap@4.5.0/dist/css/bootstrap.css' rel='stylesheet' />
<link href='https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.13.1/css/all.css' rel='stylesheet'>
{% endblock %}

{% block body %}
  <div class="row">
  <div class="col">
    <a href="/agenda/afegir?usuari={{user.id}}" class="btn btn-primary mb-3" role="button">
      {{ 'agenda.add'|trans }}
    </a>
    
    </div>
    
  </div>
  <div class="row">
    <div class="col" id="calendar-holder"></div>
  </div>
{% endblock %}

{% block javascripts %}
  <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/core@4.1.0/main.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/interaction@4.1.0/main.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/daygrid@4.1.0/main.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@fullcalendar/timegrid@4.1.0/main.min.js"></script>

  <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', () => { 
      var calendarEl = document.getElementById('calendar-holder');

    var calendar = new FullCalendar.Calendar(calendarEl, { 
      defaultView: 'dayGridWeek', 
      editable: false,
      eventSources: [ 
        { 
          url: "{{path('fc_load_events')}}", 
          method: "POST", 
          extraParams: { filters: JSON.stringify({"user_id":{{ user.id }}}) }, 
          failure: () => { 
            // alert("There was an error while fetching FullCalendar!"); 
          }, 
        },
      ], 
      header: 
      { 
        left: 'prev,next today', 
        center: 'title', 
        right: 'dayGridMonth,timeGridWeek,timeGridDay', 
      }, 
      plugins: [ 'interaction', 'dayGrid', 'timeGrid' ], // https://fullcalendar.io/docs/plugin-index
      timeZone: 'Europe/Madrid', 
      firstDay: 1,
      locale: 'es',
      themeSystem: 'bootstrap'
      }); 
      calendar.render(); 
    });
  </script>
{% endblock %}

templates/agenda/fitxa_agenda.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'agenda.fitxa'|trans }}{% endblock %}
{% block title_block %}
 {{ 'agenda.fitxa'|trans }}
{% endblock %}


{% block body %}
	<div class="row">
    	<a href="/agenda/event/modificar/{{ agenda.id }}" class="btn btn-secondary m-3" role="button">
      		{{ 'agenda.edit'|trans }}
		</a>
		<a href="/agenda/event/esborrar/{{ agenda.id }}" class="btn btn-danger m-3" role="button">
      		{{ 'agenda.del'|trans }}
		</a>
	</div> 
			<div class="card">
				<div class="card-header">
					<span>{{ 'agenda.codi'|trans }}</span>{{ agenda.id }} 
				</div>
				<div class="card-body">
					<p class="card-text">
						<b>{{ 'agenda.vehicle'|trans }}</b>
						<span>{{ agenda.vehicle }}</span>
						<span>({{ agenda.vehicle.model }})</span>
					</p>
					<p class="card-text">
					<b>{{ 'agenda.tasca'|trans }}</b>
						<span>{{ agenda.feina }}</span>
					</p>


					
					<p class="card-text">
					<b>{{ 'agenda.dataInici'|trans }}</b>
						<span>{{ agenda.dataHoraInici|format_datetime('full', 'full', locale='es') }}</span>
					</p>
					
					<p class="card-text">
						<b>{{ 'agenda.dataFi'|trans }}</b>
						<span>{{ agenda.dataHoraFi|format_datetime('full', 'full', locale='es') }}</span>
					</p>

					<p class="card-text">
						<b>{{ 'agenda.treballador'|trans }}</b>
						<span>{{ agenda.treballador }}</span>
					</p>
					<p class="card-text">
						<b>{{ 'agenda.estat'|trans }}</b>
						{% if agenda.estat == 0 %}
						<span>Pendent</span>
						{% elseif agenda.estat == 1 %}
						<span>Completada</span>
						{% else %}
						<span>Anulada</span>
						{% endif %}
					</p>
					
					
			</div>
			
			

{% endblock %}

templates/agenda/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'agenda.agendes'|trans }}
{% endblock %}
{% block title_block %}
  {{ 'agenda.agendes'|trans }}
{% endblock %}
{% block body %}
  <div class="container mt-4">
    {% for u in usuaris %}

	<a class="btn btn-outline-dark btn-lg btn-block" href="/agenda/{{u.id}}" role="button"> {{ u.nom }} {{u.cognom}}</a>
     
    {% endfor %}
	
  </div>
  <div class="container mt-4" >
  <a href="/agenda/events" class="btn btn-outline-primary btn-lg btn-block" role="button">
      {{ 'agenda.llistat'|trans }} 
    </a>
  </div>
{% endblock %}

templates/agenda/llistar.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'agenda.events'|trans }}
{% endblock %}
{% block title_block %}
  {{ 'agenda.events'|trans }}
{% endblock %}

{% block body %}
   
  <div class="table-responsive">
    <div id="events">
      Loading...
    </div>
  </div>




{% endblock %}
{% block javascripts %}
  <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>
  
  <script>
    $(function() { 
      var dt = $('#events').initDataTables(
        {{datatable_settings(datatable)}},   
        {   
          searching: true, 
          dom: 'Bfrtip', 
         // "fnDrawCallback": afegirIdFactura
        }
      );
    });

  </script>
{% endblock %}

templates/agenda/modificar_agenda.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'agenda.edit'|trans }}
{% endblock %}
{% block title_block %}
  {{ 'agenda.edit'|trans }}
{% endblock %}
{% block body %}
  <div class="pt-2">
    {{ form_start(form) }}
    {{ form_row(form.feina) }}
    {{ form_row(form.dataHoraInici) }}
    {{ form_row(form.dataHoraFi) }}
    {{ form_row(form.vehicle) }}
    {{ form_row(form.treballador) }}
    {{ form_row(form.estat) }}

    {{ form_rest(form) }}

    <div class="w-100 text-center">
      <button type="submit" class="btn btn-outline-primary">
        <i class="fa fa-paper-plane"></i> Enviar
      </button>
    </div>

    {{ form_end(form) }}
  </div>
{% endblock %}

{% block javascripts %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment-with-locales.min.js"
    integrity="sha512-LGXaggshOkD/at6PFNcp2V2unf9LzFq6LE+sChH7ceMTDP0g2kn6Vxwgg7wkPP7AAtX+lmPqPdxB47A0Nz0cMQ=="
    crossorigin="anonymous"></script>
    <script src="/build/bootstrap-datetimepicker.min.js"></script>
  <script type="text/javascript"
    src="/build/bootstrap-datetimepicker.es.js"
    charset="UTF-8"></script>

  
  <script>
    $(document).ready(function () { $(".form_datetime").datetimepicker({
    language: 'es' }); })
  </script>
{% endblock %}