src/Entity/Vehicle.php
<?php

namespace App\Entity;

use App\Repository\VehicleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VehicleRepository::class)
 */
class Vehicle
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=15,unique=true)
     */
    private $Matricula;




    /**
     * @ORM\Column(type="float")
     */
    private $Kilometres;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="vehicles")
     */
    private $client;

    /**
     * @ORM\ManyToOne(targetEntity=Model::class, inversedBy="vehicles")
     */
    private $Model;

    /**
     * @ORM\OneToMany(targetEntity=Pressupost::class, mappedBy="vehicle")
     */
    private $pressuposts;

    /**
     * @ORM\OneToMany(targetEntity=OrdreReparacio::class, mappedBy="vehicle")
     */
    private $ordreReparacios;

    /**
     * @ORM\OneToMany(targetEntity=Factura::class, mappedBy="vehicle")
     */
    private $facturas;

    /**
     * @ORM\OneToMany(targetEntity=Agenda::class, mappedBy="vehicle")
     */
    private $agendas;



    public function __construct()
    {
        $this->pressuposts = new ArrayCollection();
        $this->ordreReparacios = new ArrayCollection();
        $this->facturas = new ArrayCollection();
        $this->agendas = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatricula(): ?string
    {
        return $this->Matricula;
    }

    public function setMatricula(string $Matricula): self
    {
        $this->Matricula = $Matricula;

        return $this;
    }






    public function getKilometres(): ?float
    {
        return $this->Kilometres;
    }

    public function setKilometres(float $Kilometres): self
    {
        $this->Kilometres = $Kilometres;

        return $this;
    }

    public function getClient(): ?Client
    {
        return $this->client;
    }

    public function setClient(?Client $client): self
    {
        $this->client = $client;

        return $this;
    }

    public function getModel(): ?Model
    {
        return $this->Model;
    }

    public function setModel(?Model $Model): self
    {
        $this->Model = $Model;

        return $this;
    }

    /**
     * @return Collection|Pressupost[]
     */
    public function getPressuposts(): Collection
    {
        return $this->pressuposts;
    }

    public function addPressupost(Pressupost $pressupost): self
    {
        if (!$this->pressuposts->contains($pressupost)) {
            $this->pressuposts[] = $pressupost;
            $pressupost->setVehicle($this);
        }

        return $this;
    }

    public function removePressupost(Pressupost $pressupost): self
    {
        if ($this->pressuposts->removeElement($pressupost)) {
            // set the owning side to null (unless already changed)
            if ($pressupost->getVehicle() === $this) {
                $pressupost->setVehicle(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Matricula;
    }

    /**
     * @return Collection|OrdreReparacio[]
     */
    public function getOrdreReparacios(): Collection
    {
        return $this->ordreReparacios;
    }

    public function addOrdreReparacio(OrdreReparacio $ordreReparacio): self
    {
        if (!$this->ordreReparacios->contains($ordreReparacio)) {
            $this->ordreReparacios[] = $ordreReparacio;
            $ordreReparacio->setVehicle($this);
        }

        return $this;
    }

    public function removeOrdreReparacio(OrdreReparacio $ordreReparacio): self
    {
        if ($this->ordreReparacios->removeElement($ordreReparacio)) {
            // set the owning side to null (unless already changed)
            if ($ordreReparacio->getVehicle() === $this) {
                $ordreReparacio->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Factura[]
     */
    public function getFacturas(): Collection
    {
        return $this->facturas;
    }

    public function addFactura(Factura $factura): self
    {
        if (!$this->facturas->contains($factura)) {
            $this->facturas[] = $factura;
            $factura->setVehicle($this);
        }

        return $this;
    }

    public function removeFactura(Factura $factura): self
    {
        if ($this->facturas->removeElement($factura)) {
            // set the owning side to null (unless already changed)
            if ($factura->getVehicle() === $this) {
                $factura->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Agenda[]
     */
    public function getAgendas(): Collection
    {
        return $this->agendas;
    }

    public function addAgenda(Agenda $agenda): self
    {
        if (!$this->agendas->contains($agenda)) {
            $this->agendas[] = $agenda;
            $agenda->setVehicle($this);
        }

        return $this;
    }

    public function removeAgenda(Agenda $agenda): self
    {
        if ($this->agendas->removeElement($agenda)) {
            // set the owning side to null (unless already changed)
            if ($agenda->getVehicle() === $this) {
                $agenda->setVehicle(null);
            }
        }

        return $this;
    }

    /**
     * String representation of object
     * @return string the string representation of the object or null
     */
    public function serialize()
    {
        return serialize([
            $this->id,
            $this->Matricula,
        ]);
    }
}

src/Controller/FacturaController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\{Pressupost, Article, Factura, Empresa, OrdreReparacio};
use App\Manager\FacturaManager;
use App\Form\{FacturaType, LiniaFacturaType};
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\QueryBuilder;

use Omines\DataTablesBundle\Column\TextColumn;
use Omines\DataTablesBundle\DataTableFactory;
use Omines\DataTablesBundle\Adapter\Doctrine\ORMAdapter;

use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
use Symfony\Component\HttpFoundation\JsonResponse;

class FacturaController extends BaseController
{
    /**
     * @Route("/factures", name="llistar_factures")
     */
    public function llistar_factures(Request $request, DataTableFactory $dataTableFactory): Response
    {
        $table = $dataTableFactory->create()

            ->add('vehicle', TextColumn::class, ['label' => 'Vehicle', 'searchable' => True, 'field' => 'vehicle.Matricula'])
            ->add('client', TextColumn::class, ['label' => 'Client', 'searchable' => True, 'field' => 'client.DNI'])
            ->add('treballador', TextColumn::class, ['label' => 'Treballador', 'field' => 'treballador.nom'])
            ->add('ordre', TextColumn::class, ['label' => 'Ordre de reparació', 'searchable' => True, 'field' => 'ordre.id'])
            ->add('estat', TextColumn::class, ["visible" => false, 'label' => 'Estat pagament', 'render' => function ($value, $context) {
                $action = "";
                if ($value == 0) {
                    $action = "<p class='text-danger'>No pagada</p>";
                } else {
                    $action = "<p class='text-success'>Pagada</p>";
                }

                return $action;
            }])
            ->add('id', TextColumn::class, ['label' => 'ID', 'searchable' => True, 'orderable' => True, 'render' => function ($value, $context) {


                $action = "";
                if ($value <= 9) {
                    $value = '0' . $value;
                }

                $action = $action . '<span class="badge bg-light text-dark mr-2">' . $value . '</span>' . ' 
                        <div class="btn-group">
                            <a href="/factures/' . $value . '" class="badge badge-info p-2 m-1">Veure factura</a>
                            <a href="/factures/modificar/' . $value . '" class="badge badge-secondary p-2 m-1">Modificar factura</a>
                            <a href="/factures/' . $value . '/pdf" class="badge badge-success p-2 m-1">Generar pdf</a>
                        </div>';
                if (!$context->getEstat()) {
                    $action = $action . '<a  data-toggle="modal" data-target="#modalPagar"   data-id-factura="' . $value . '" class="botoModelPagar badge badge-primary p-2 m-1">Pagar</a>';
                }

                return $action;
            }])
            ->addOrderBy(5, 'desc')
            ->createAdapter(ORMAdapter::class, [
                'entity' => Factura::class,
                'query' => function (QueryBuilder $builder) {
                    $builder
                        ->select('factura')
                        ->from(Factura::class, 'factura')
                        ->leftJoin('factura.vehicle', 'vehicle')
                        ->leftJoin('vehicle.client', 'client')
                        ->leftJoin('factura.ordre', 'ordre')
                        ->leftJoin('factura.treballador', 'treballador')
                        ->distinct('factura');
                }
            ])
            ->handleRequest($request);

        if ($table->isCallback()) {
            return $table->getResponse();
        }

        return $this->render('factura/index.html.twig', ['datatable' => $table]);
    }

    /**
     * @Route("/factures/afegirLinia",name="afegir_linia_factura")
     */
    public function createLinia(Request $request): Response
    {

        $id_factura = $request->request->get('id_factura');
        $total_linia = $request->request->get('total_linia');
        $factura = $this->getDoctrine()->getRepository(Factura::class)->findOneBy(['id' => $id_factura]);
        //Comprovacions de pressupost correcte

        $articles =  $this->getDoctrine()->getRepository(Article::class)->findAll();
        return $this->render('factura/parcial/formLinia.html.twig', ['total_linia' => $total_linia, 'articles' => $articles]);
    }

    /**
     * @Route("factures/{id}/pagar", name="pagar_factura")
     */
    public function pagarFactura(Request $request, Factura $factura): Response
    {
        //$id_factura = $request->request->get('id');
        $tipus_pagament = $request->request->get('tipusPagament');

        //$factura = $this->getDoctrine()->getRepository(Factura::class)->findOneBy(['id' => $id_factura]);
        if ($factura->getEstat() == 0 && !is_null($tipus_pagament)) {
            $factura->pagar($tipus_pagament);
            $this->save($factura);
            return new Response("ok", Response::HTTP_OK);
        }
        return new Response("ko", Response::HTTP_FORBIDDEN);
    }
    /**
     * @Route("factures/estadistiques", name="estad_factures")
     */
    public function estadistiques(): Response
    {
        $repository = $this->getDoctrine()
            ->getRepository(Factura::class);
        $dades = $repository->topClient();
        return $this->render('factura/estadistiques.html.twig', ['dades'=>$dades]);
    }

    /**
     * @Route("/factures/afegir/{ordre}",name="afegir_factura")
     */
    public function createFactura(Request $request, FacturaManager $facturaManager,  UserInterface $user, OrdreReparacio $ordre): Response
    {
        if ($ordre->esFacturable()) {
            $entityManager = $this->obManager();
            $articles = $this->getDoctrine()
                ->getRepository(Article::class)
                ->findAll();

            $factura = new Factura();



            $date = new \DateTime('@' . strtotime('now'));
            $factura->setAny($date->format('Y'));
            $factura->setData($date);
            $factura->setTotal(0);
            $factura->setTreballador($user);
            $factura->setOrdre($ordre);
            $factura->setTasca($ordre->getTasca());
            $factura->setQuilometres($ordre->getQuilometres());
            $factura->setVehicle($ordre->getVehicle());
            //$factura->setEstat(False);
            //$factura->setFormaPagament(NULL);
            $ordre->setFactura($factura);


            $form = $this->createForm(FacturaType::class, $factura);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {

                $noves_linies = $request->request->get('new_linia');
                $facturaManager->saveFactura($factura, $noves_linies);
                $this->save($ordre);
                $this->addFlash('success', 'factura.success-add');

                return $this->redirectToRoute('llistar_factures', array("id" => $factura->getId()));
            }

            return $this->render('factura/afegir.html.twig', ['form' => $form->createView(), 'articles' => $articles]);
        } else {
            return $this->redirectToRoute('llistar_factures');
        }
    }

    /**
     * @Route("factures/{id}", name="factura_show")
     */
    public function show(Factura $factura): Response
    {
        $empresa = $this->getDoctrine()
            ->getRepository(Empresa::class)
            ->findOneBy(['id' => 1]);

        return $this->render('factura/fitxa_factura.html.twig', [
            'factura' => $factura,
            'empresa' => $empresa
        ]);
    }


    /**
     * @Route("factures/{id}/pdf", name="factura_pdf")
     */
    public function pdfAction(Pdf $pdf, Factura $factura)
    {
        $empresa = $this->getDoctrine()
            ->getRepository(Empresa::class)
            ->findOneBy(['id' => 1]);

        $html = $this->renderView('factura/fitxa_factura_pdf.html.twig', [
            'controller_name' => 'PressupostController',
            'factura' => $factura,
            'empresa' => $empresa,
        ]);
        $nomFitxer = "factura" . $factura->getId() . ".pdf";
        return new PdfResponse(
            $pdf->getOutputFromHtml($html),
            $nomFitxer
        );
    }

    /**
     * @Route("factures/modificar/{id}", name="modificar_factura")
     */
    public function modificarFactura(Request $request, Factura $factura, FacturaManager $facturaManager): Response
    {
        if ($factura->getEstat() == 0) {

            $form = $this->createForm(FacturaType::class, $factura);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $noves_linies = $request->request->get('new_linia');
                $facturaManager->saveFactura($factura, $noves_linies);
                $this->addFlash('success', 'factura.success-edit');
                return $this->redirectToRoute('llistar_factures');
            }

            return $this->render('factura/modificar_factura.html.twig', ['form' => $form->createView(), 'factura' => $factura]);
        } else {
            $this->addFlash('danger', 'factura.error-edit');
            return $this->redirectToRoute('llistar_factures');
        }
    }
}

templates/factura/afegir.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'factura.add'|trans }}
{% endblock %}
{% block title_block %}
  {{ 'factura.add'|trans }}
{% endblock %}

{% block body %}
  <div class="container mt-4">
    <div class="pt-2">
      {{ form_start(form) }}
      <div class="row">
        <div class="col">
          {{ form_row(form.any) }}
        </div>
        <div class="col">
          {{ form_row(form.data) }}
        </div>
      </div>
      {{ form_row(form.tasca) }}
      <div class="row">
        <div class="col">
          {{ form_row(form.quilometres) }}
        </div>
        <div class="col">
          {{ form_row(form.iva) }}
        </div>
      </div>
      <div class="row">
        <div class="col">
          {{ form_row(form.vehicle) }}
        </div>
        <div class="col">
          {{ form_row(form.treballador) }}
        </div>
      </div>
      <div class="row">
        <div class="col">
          {{ form_row(form.estat) }}
        </div>
        <div class="col">
          {{ form_row(form.formaPagament) }}
        </div>
      </div>
      <div class="row">
        <div class="col">
          {{ form_row(form.observacions) }}
        </div>
      </div>

      <div clas="row">
        {{ form_row(form.liniaFacturas) }}
        <button class="btn btn-primary add_linia_fac"
          data-id-factura="{{ form.vars.data.id }}">
          Afegir linia
        </button>
      </div>
      <div id="linias"></div>

     <!-- {{ form_rest(form) }}-->

      <div class="w-100 text-center">
        <button type="submit" class="btn btn-outline-primary">
          <i class="fa fa-paper-plane"></i>Guardar
        </button>
        <!--<a href="/factures/?pagar" class="btn btn-outline-secondary">Pagar</a>-->
        <!--<button type="submit" id="pagarFactura" data-id-factura="{{ form.vars.data.id }}" class="btn btn-outline-secondary">
          <i class="fa fa-paper-plane"></i>Pagar
        </button>-->

        
      </div>

      {{ form_end(form) }}
    </div>
  </div>
{% endblock %}

templates/factura/estadistiques.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ 'estadistiques.estadistiques'|trans }}!{% endblock %}

{% block body %}
<div id="container" style="width:100%; height:400px;"></div>

{% endblock %}

{% block javascripts %}
<script src="https://code.highcharts.com/highcharts.js"></script>
<script> 
document.addEventListener('DOMContentLoaded', function () {
        const chart = Highcharts.chart('container', {
            chart: {
                type: 'column'
            },
            title: {
                text: 'Vehicle més factures'
            },
            
            xAxis: {
                categories: [
                   'Matricula vehicle'
                ],
                crosshair: true
            },
            yAxis: {
                min: 0,
                title: {
                    text: '# factures'
                }
            },
            /*tooltip: {
                headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
                pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                    '<td style="padding:0"><b>{point.y:.1f} mm</b></td></tr>',
                footerFormat: '</table>',
                shared: true,
                useHTML: true
            },
            plotOptions: {
                column: {
                    pointPadding: 0.2,
                    borderWidth: 0
                }
            },*/
            series: [
                {% for d in dades %}
                    {
                        name:'{{ d.Matricula }}',
                        data:[{{ d.1 }}]
                    },
                   {% endfor %}
                ]
        });
    });
    </script>
    {% endblock %}

templates/factura/fitxa_factura.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'factura.facturaNum'|trans }} {{ factura.id }}
{% endblock %}
{% block title_block %}
  {{ 'factura.facturaNum'|trans }} {{ factura.id }}
  
{% endblock %}

{% block body %}
<!-- Modal pagar factura -->
<div class="modal fade" id="modalPagar" tabindex="-1" role="dialog" aria-labelledby="modalPagarLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalPagarLabel">{{ 'factura.pagar'|trans }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
    
          <div class="form-group col-sm">
              <label>{{ 'factura.pagament'|trans }}</label>
              <select class="form-control" id="tipusPagament" />
                  
                      <option value="0">{{ 'factura.efectiu'|trans }}</option>
                      <option value="1">{{ 'factura.targeta'|trans }}</option>
                      <option value="2">{{ 'factura.xec'|trans }}</option>

                  
              </select>   
          </div>   
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" data-id-factura="{{ factura.id }}" class="btn btn-primary pagarFactura">Pagar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>
{% if not factura.estat %}
          <a  data-toggle="modal" data-target="#modalPagar"   data-id-factura="  {{ factura.id }} " class="text-rigth badge badge-info p-2 m-1">Pagar</a>
        
        {% endif %}

  


  <div class="pt-2">
    <div class="row">
      <div class="col card border-dark">
        <!--          <img src="images/{{ empresa.logo }}"
          clas="img-thumbnail"
          width="75"
          heigth="75"
          alt="Logo empresa" />         -->

        {{ empresa.nom }}<br />
        {{ empresa.nif }}<br />
        {{ empresa.direccio }}<br />
        {{ empresa.codipostal }}
        {{ empresa.ciutat }}<br />
        {{ empresa.provincia }}<br />
        {{ empresa.telefon }}
      </div>

      <div class="col card border-dark pl-1">
        <p>
          <b>{{ 'client.client'|trans }}:</b>
          {{ factura.vehicle.client.id }} -
          {{ factura.vehicle.client.nom }}
          {{ factura.vehicle.client.cognoms }}
        </p>
        <p>
          <b>{{ 'client.info.adreca'|trans }}:</b>
          {{ factura.vehicle.client.adreca }}
          {{ factura.vehicle.client.CP }}
          {{ factura.vehicle.client.ciutat }}
        </p>
        <p>
          <b>{{ 'client.info.tel'|trans }}:</b>
          {{ factura.vehicle.client.telefon }}
        </p>
        <p>
          <b>{{ 'client.info.mail'|trans }}:</b>
          {{ factura.vehicle.client.email }}
        </p>
      </div>
    </div>
    <div class="row mt-2">
      <div class="col">
        <b>{{ 'form.any'|trans }}</b>
        {{ factura.any }}
      </div>
      <div class="col">
        <b>{{ 'factura.facturaNum'|trans }}</b> {{ factura.id }}
      </div>

      <div class="col">
        <b>{{ 'form.data'|trans }}</b>
        {{ factura.data|date('d/m/Y') }}
      </div>
    </div>

    <div class="row">
      <div class="col">
        <b>{{ 'ordre.ordre'|trans }}:</b>
        {{ factura.ordre.id }}
      </div>
      <div class="col">
        <b>{{ 'form.iva'|trans }}</b>
        {{ factura.iva }}
      </div>
      <div class="col">
        <b>{{ 'form.estat'|trans }}</b>
        {% if factura.estat %}
          Pagada
        {% else %}
          No Pagada
        {% endif %}
      </div>
    </div>
    <div class="row mb-2">
      <div class="col">
        <b>{{ 'form.matricula'|trans }}</b>
        {{ factura.vehicle }}
      </div>
      <div class="col">
        <b>{{ 'form.treballador'|trans }}</b>{{ factura.treballador }}
      </div>
    </div>

    <div class="row mt-4">
      <div class="col card border-dark">
        <b>{{ 'form.tasca'|trans }}</b>
        <p>
          {{ factura.tasca }}
        </p>
      </div>
    </div>

    <div class="row text-center mt-4 bg-secondary text-white text-uppercase">
      <div class="col">
        <b class="mb-2">{{ 'form.articles'|trans }}</b>
      </div>
    </div>

    <div class="row mt-2">
      <table class="table">
        <thead>
          <tr>
            <th scope="col">
              {{ 'article.referencia'|trans }}
            </th>
            <th scope="col">
              {{ 'article.article'|trans }}
            </th>
            <th scope="col">
              {{ 'article.quantitat'|trans }}
            </th>
            <th scope="col">
              {{ 'article.preu'|trans }}
            </th>
            <th scope="col">
              {{ 'article.descompte'|trans }}
            </th>
            <th scope="col">
              {{ 'article.total'|trans }}
            </th>
          </tr>
        </thead>
        <tbody>
          {% for l in factura.liniaFacturas %}
            <tr>
              <th scope="row">
                {{ l.article.referencia }}
              </th>
              <td>
                <span>{{ l.article }}</span>
              </td>
              <td>
                <span>{{ l.quantitat }}</span>
              </td>
              <td>
                <span>{{ l.preu }}</span>
              </td>
              <td>
                {% if l.descompte != 0 %}
                  <span>{{ l.descompte }}</span>
                {% endif %}
              </td>
              <td>
                <span>
                  {{ l.preu * l.quantitat
                    - l.preu * l.quantitat * l.descompte / 100 * 1 }}
                </span>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>

    <div class="mt-5">
      <div class="row bg-secondary text-white text-center text-uppercase">
        <div class="col">
          <p>
            {{ 'factura.baseImposable'|trans }}
          </p>
        </div>
        <div class="col">
          <p>
            {{ 'factura.IVA'|trans }}
          </p>
        </div>
        <div class="col text-right">
          <p>
            {{ 'factura.total'|trans }}
          </p>
        </div>
      </div>

      <div class="row bg-light text-center">
        <div class="col">
          <p>
            {{ factura.total }} €
          </p>
        </div>
        <div class="col">
          <p>
            {{ factura.iva * 100 }}%
          </p>
        </div>
        <div class="col text-right">
          <b>{{ factura.total * (1 + factura.iva) }} €</b>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <p class="text-justify">
          {{ 'factura.observacions'|trans }}:
        </p>
        <p class="text-justify">
          {{ factura.observacions }}
        </p>
      </div>
    </div>

    <div class="row">
      <div class="col">
        <p class="text-justify">
          {{ 'factura.pagament'|trans }}:{% if factura.formaPagament is null %}
            {{ 'factura.noPagat'|trans }}
          {% elseif factura.formaPagament == 0 %}
            {{ 'factura.efectiu'|trans }}
          {% elseif factura.formaPagament == 1 %}
            {{ 'factura.targeta'|trans }}
          {% elseif factura.formaPagament == 2 %}
            {{ 'factura.xec'|trans }}
          {% endif %}
        </p>
      </div>
    </div>
    <hr />

    <div class="row">
      <div class="col">
        <p class="text-justify lh-1 font-10">
          {{ 'factura.legal'|trans }}
        </p>
        <p class="text-justify lh-1 font-10">
          Responsable fitxer: {{ empresa.nom }} NIF: {{ empresa.nif }} Dir. postal:
          {{ empresa.direccio }} {{ empresa.codipostal }} {{ empresa.ciutat }}
          ({{ empresa.provincia }}) Telèfon: {{ empresa.telefon }} En nom de l'empresa
          tactem la informació que ens facilita amb la finalitat de prestar els serveis
          sol·licitats i realitzar la factura del mateix. Les dades proporcionades
          s'emmagatzemaran durant la relació comercial o els anys marcats per la
          llei. Les dades no es cediran a tercers llevat en els casos que existeixi
          obligació legal. Té dret a la possiblitat d'exercir els seus drets d'accés,
          rectificació, cancel·lació i oposició, limitació del tractament, portabilitat
          de les dades i a no ser objecte de decisions individualitzades automatitzades
          mitjançant el correu electrònic: {{ empresa.email }}
        </p>
      </div>
    </div>
  </div>
{% endblock %}

templates/factura/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  {{ 'factura.list'|trans }}
{% endblock %}
{% block title_block %}
  {{ 'factura.list'|trans }}
{% endblock %}

{% block body %}
  <!-- <div class="row">
    <a href="/factures/afegir" class="btn btn-primary m-3" role="button">
      {{ 'factura.add'|trans }}
    </a>
  </div> -->
  <div class="table-responsive">
    <div id="factures">
      Loading...
    </div>
  </div>



<!-- Modal pagar factura -->
<div class="modal fade" id="modalPagar"  tabindex="-1" role="dialog" aria-labelledby="modalPagarLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modalPagarLabel">{{ 'factura.pagar'|trans }}</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="row">
    
          <div class="form-group col-sm">
              <label>{{ 'factura.pagament'|trans }}</label>
              <select class="form-control" id="tipusPagament" />
                  
                      <option value="0">{{ 'factura.efectiu'|trans }}</option>
                      <option value="1">{{ 'factura.targeta'|trans }}</option>
                      <option value="2">{{ 'factura.xec'|trans }}</option>

                  
              </select>   
          </div>   
        </div>
      </div>
      <div class="modal-footer">
        <button type="button"  data-id-factura="55" class="botoPagar btn btn-primary pagarFactura">Pagar</button>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        
      </div>
    </div>
  </div>
</div>

{% endblock %}
{% block javascripts %}
  <script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
  <script src="{{ asset('bundles/datatables/js/datatables.js') }}"></script>
  
  <script>
    $(function() { 
      var dt = $('#factures').initDataTables(
        {{datatable_settings(datatable)}},   
        {   
          searching: true, 
          dom: 'Bfrtip', 
          "fnDrawCallback": afegirIdFactura
        }
      );
    });
function afegirIdFactura(){      

    $('.botoModelPagar').on("click", function (e) {
      console.log("hola")
      var idFactura = $(this).attr('data-id-factura')
      console.log(idFactura)
      $('.botoPagar').attr('data-id-factura',idFactura)
      });

      
    }

    

  </script>
{% endblock %}